name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{runner.os}}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test with pytest
        run: pytest tests/

  lint-and-format:
    name: Lint & Format Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install linting tools
        run: pip install ruff black

      - name: Check formatting with Black
        run: black --check .

      - name: Lint With Ruff
        run: ruff check .

  deploy-to-huggingface:
    name: Push to Hugging Face Hub
    needs: [test, lint-and-format]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{secrets.HF_TOKEN}}
          HF_USERNAME: "ArturAgababyanML"
          HF_SPACE_NAME: "projt5"
        run: |
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main:main --force
